### ISSUE TITLE
Footer Padding needs to take in EdgeInsetsGeometry instead of double

### ISSUE THREAD

**Issue by zoomzoomTnT** [nyakaz73/Flutter-Footer#1]
`Footer(
          backgroundColor: Colors.blue[400],
          padding: 50,
          child: ...`

Padding only takes double, please change it to EdgeInsetsGeometry instead so that one can use `EdgeInsets.symmetric(horizontal: 100)`

**Comment by nyakaz73** [comment]
Hi @zoomzoomTnT thank you for the feedback. I have updated the Footer padding to take the EdgeInsetsGeometry instead of double you can check it out on the documentation of the new version footer version .0.3 here https://pub.dev/documentation/footer/latest/footer/Footer-class.html.
Again thank you for your contribution.
